### ISSUE TITLE
Throttling core in case of cache miss 

### ISSUE THREAD

**Issue by SoCScholar** [openhwgroup/cva6#1527]
### Is there an existing CVA6 bug for this?

- [X] I have searched the existing bug issues

### Bug Description

I have been wondering for a long time how to throttle the core if (any of the multicore) core accesses more memory. I am implementing bandwidth regulation for Real-time purposes in CVA6 multicore. At this moment I want to stick to a single core, L1 cache. Later I will go to L2 cache and multicore if it works in a single core.   

Do you know any of the following tricks that can be suitable for throttling the CPU core like for example : 
 
1.	block icache + dcache in submitting requests to the memory subsystem on cache misses so it prevents from accessing any data  (this keeps the core running as long as its working set is in the caches)
         
         
2.	insert some fake blocking in the icache
   so the icache does not deliver the next cacheline on a fetch to the core 
   

3.	inserting pipeline bubbles in the instruction decoder
   - as long as throttling is assert
   - insert a fixed amount of bubbles, then ignore throttling for a fixed amount
     to guarantee minimum progress 

Which tricks would be most convenient to apply in CVA6 and How to apply them? Or there can be better than this. My idea is to throttle the non-real-time core so that if there a real-time need for more bandwidth.

**Comment by JeanRochCoulon** [comment]
César, @HimalSubedi787 is searching a way to chalenge the cache. These points can be good inputs for your cache verification. I assigned you to this point as you are the more active on this topic so far.

**Comment by cfuguet** [comment]
Hi @HimalSubedi787,

From your proposals, I prefer the first solution because it allows the core to do some computation while being throttled if it does not access the memory. The other two solutions, stalls the core whether it does access the memory or not.

A fourth solution would be to a add a throttle mechanism at the input of the NoC (between the output of the cache and the NoC). It has the advantage of being independent to the cache, and then can be used with any of the three cache subsystems proposed with the CVA6 (WT, WB, HPDcache). It also has the advantage that it works even if the core implements more than 1 level or private caches (like in the multi-core OpenPiton environment where the CVA6 has 2 levels of private caches).

Best regards
