### ISSUE TITLE
Read-only 0 CSRs

### ISSUE THREAD

**Issue by JeanRochCoulon** [openhwgroup/cva6#2192]
MHPMEVENT wrong legal value:
![image](https://github.com/openhwgroup/cva6/assets/56552370/90ce41b5-e68c-42fc-bfa1-8ba4d04e22c4)

MHPCOUNTERS/H wrong legal value:
![image](https://github.com/openhwgroup/cva6/assets/56552370/37af38bb-c66f-47fd-9393-55e5dfb59f24)

MCYCLE/H, MINSTRET/H are RW registers. Legal value should be specified as follow: [0x00000000..0xFFFFFFFF]
![image](https://github.com/openhwgroup/cva6/assets/56552370/58392f8d-357c-4cf4-a23a-e564dd2d6f38)

MTVEC is RW CSR
![image](https://github.com/openhwgroup/cva6/assets/56552370/2105ef84-168a-4cd9-9588-01cfc99d63ef)

The MCAUSE legal_values are wrong, to be discussed with  @ASintzoff
![image](https://github.com/openhwgroup/cva6/assets/56552370/d045570f-cecd-42c2-b6a3-58e0c79daa2d)

The MTVAL CSR is read only 0, so ROCST
![image](https://github.com/openhwgroup/cva6/assets/56552370/9626209a-8a36-4928-9970-b5b3df5ee2b3)

**Comment by zchamski** [comment]
In #2206 the `riscv-config` spec was adjusted so that after applying the doc generation script:
- `MTVAL` is RO_CONSTANT zero.
- `MHPMEVENT*`, `MHPCOUNTER*` and MCOUNTINHIBIT` are RO_CONSTANT zero.

For the legal value range of `MCYCLE`/`MCYCLEH` we need to adjust the presentation than the spec.

`Handling of bitmasked fields like `MTVEC` (in this case: bit zero always ignored on write, always cleared on read), the rendering needs additional information that is currently dropped when parsing input coming from `riscv-config`.

**Comment by JeanRochCoulon** [comment]
#2231 fixed MTVAL RTL issue

**Comment by JeanRochCoulon** [comment]
These above modifications have been added to the CSR specification. The PR can be closed.
