### ISSUE TITLE
Make verilate exiting due to many errors in makefile 

### ISSUE THREAD

**Issue by vasilistheod** [openhwgroup/cva6#571]
Hello everyone , i need to build the verilator model of cva6 (ariane).. i have followed all the instructions in the cva6 repository but when i do: make verilate so that i can build the verilator model it exits due to too many errors in the makefile.. i have searched a lot and i cant find the solution ..please someone help me , i would also appreciate if you suggested any other cores so that i can build easily the verilator mode
![Screenshot (18)](https://user-images.githubusercontent.com/73837338/101955099-dd493e80-3c05-11eb-8872-d7b1099236a7.png)
l

**Comment by zarubaf** [comment]
On which Verilator version are you? I remember the default Ubuntu version to be _very_ old. I recommend at least some version `> 4.0`.

**Comment by MikeOpenHWGroup** [comment]
Thanks for your insight @zarubaf.

Hi @vasilistheod , thanks for your interest in CVA6. Personally, I use Verilator v4.100 for CVA6.  Since this issue has not been updated in more than two years, so I will assume it is resolved and will close this issue. If you are still having trouble, please feel free to open another.
